#ifndef BINDINGS_INC
#define BINDINGS_INC

const int MAX_INSTANCES = 100;
const int MAX_LIGHTS = 100;

const int TOP_LEVEL_ACC_SET = 0;
const int TOP_LEVEL_ACC_BINDING = 0;

const int MATERIAL_SET = 0;
const int MATERIAL_BINDING = 1;

const int OUTPUT_IMG_SET = 0;
const int OUTPUT_IMG_BINDING = 2;

const int LIGHTS_SET = 0;
const int LIGHTS_BINDING = 3;

const int VERTEX_ATTR_SET = 1;
const int VERTEX_ATTR_BINDING = 0;

const int INDICES_SET = 2;
const int INDICES_BINDING = 0;

#endif