repo_paths:
  build_root: "_build"
  logs_root: "_logs"
  conan_lock: "conan_glfw.lock"
  conan_deps_root: "{build_root}/{platform}/deps"

build:
  windowing: "glfw"
  prebuild:
    format: {}
    slangc:
      shaders:
        - input: "assets/shaders/test/*.slang"
          output: "assets/shaders/test/*.wgsl"
    embed:
      template: "core/templates/embedded_resources.h.j2"
      resources:
        - input:
            - "core/shaders/*.*"
          output: "core/generated/embedded_resources.h"
          namespace: "core_resources"
        - input:
            - "editor/shaders/**/*.*"
            - "editor/icons/*.*"
          output: "editor/generated/embedded_resources.h"
          namespace: "editor_resources"
        - input:
            - "assets/shaders/test/simple.wgsl"
          output: "core/tests/generated/embedded_test_resources.h"
          namespace: "test_resources"
  postbuild: {}
  conan:
    local_recipes: "tools/conan"
