"""Emit a C++ header mapping (canonical defines -> filename suffix).

Reads the variant list declared in ``slangc.shaders[].variants`` and produces
a header consumed by EmbeddedCompiler so it can translate a
``compile(source_key, defines)`` request to the pre-compiled variant key.
The canonical form matches ``canonical_defines()`` in slangCompiler.cpp:
sorted, each define followed by '\\n'.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import click

from repo_tools.core import (
    RepoTool,
    ToolContext,
    logger,
    resolve_path,
)


def _canonical_defines(defines: list[str]) -> str:
    return "".join(d + "\n" for d in sorted(defines))


def _collect_variants(config: dict) -> list[tuple[str, str]]:
    """Return unique (defines_canon, suffix) pairs from slangc.shaders."""
    shaders = config.get("slangc", {}).get("shaders", []) or []
    pairs: dict[str, str] = {}
    for idx, shader in enumerate(shaders):
        if not isinstance(shader, dict):
            raise ValueError(
                f"Invalid shader entry at index {idx}: "
                f"expected dict, got {type(shader).__name__} ({shader!r})"
            )
        variants = shader.get("variants")
        if variants is None:
            variants = [{
                "defines": list(shader.get("defines", [])),
                "suffix": "",
            }]
        for variant in variants:
            if not isinstance(variant, dict):
                raise ValueError(
                    f"Invalid variant entry in shader at index {idx}: "
                    f"expected dict, got {type(variant).__name__} ({variant!r})"
                )
            defines = list(variant.get("defines", []))
            suffix = str(variant.get("suffix", ""))
            # Skip the implicit base variant — EmbeddedCompiler returns
            # the source_key unchanged when defines is empty.
            if not defines and not suffix:
                continue
            canon = _canonical_defines(defines)
            existing = pairs.get(canon)
            if existing is not None and existing != suffix:
                raise ValueError(
                    f"Variant defines {defines} registered with conflicting "
                    f"suffixes: {existing!r} vs {suffix!r}"
                )
            pairs[canon] = suffix
    return sorted(pairs.items())


def _escape_c_string(s: str) -> str:
    out: list[str] = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\x{ord(ch):02x}")
        else:
            out.append(ch)
    return "".join(out)


def _render_header(namespace: str, variants: list[tuple[str, str]]) -> str:
    ns_parts = namespace.split("::")
    open_ns = "".join(f"namespace {p} {{\n" for p in ns_parts)
    close_ns = "".join(f"}}  // namespace {p}\n" for p in reversed(ns_parts))

    if not variants:
        entries_block = "    // No registered variants.\n"
        size = 0
    else:
        lines: list[str] = []
        for canon, suffix in variants:
            lines.append(
                f'    {{"{_escape_c_string(canon)}", "{_escape_c_string(suffix)}"}},'
            )
        entries_block = "\n".join(lines) + "\n"
        size = len(variants)

    return f"""#pragma once

// Auto-generated by pts shader_variants_codegen tool - DO NOT EDIT

#include <array>
#include <string_view>

{open_ns}
struct Variant {{
    // Sorted defines joined with '\\n' — matches canonical_defines() in
    // slangCompiler.cpp so runtime lookup can hash-compare directly.
    std::string_view defines_canon;
    // Filename suffix inserted before the extension on the source_key
    // (e.g. "_no_debug" maps forward.wgsl -> forward_no_debug.wgsl).
    std::string_view suffix;
}};

inline constexpr std::array<Variant, {size}> k_variants = {{{{
{entries_block}}}}};

{close_ns}"""


def _compute_manifest(variants: list[tuple[str, str]], namespace: str) -> str:
    return json.dumps({"namespace": namespace, "variants": variants}, sort_keys=True)


class ShaderVariantsCodegenTool(RepoTool):
    name = "shader_variants_codegen"
    help = "Emit a C++ header of registered shader variants"

    def setup(self, cmd: click.Command) -> click.Command:
        cmd = click.option(
            "-f",
            "--force",
            is_flag=True,
            default=None,
            help="Regenerate even if the variant set is unchanged",
        )(cmd)
        return cmd

    def default_args(self, tokens: dict[str, str]) -> dict[str, Any]:
        return {"force": False}

    def execute(self, ctx: ToolContext, args: dict[str, Any]) -> None:
        root = ctx.workspace_root
        config = ctx.config
        tokens = ctx.tokens

        output_value = args.get("output")
        if not output_value:
            raise ValueError(
                "shader_variants_codegen: 'output' must be set in config.yaml"
            )
        namespace = str(args.get("namespace", "pts::rendering::variants"))

        variants = _collect_variants(config)
        output_path = resolve_path(root, str(output_value), tokens)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        manifest_path = output_path.with_suffix(output_path.suffix + ".manifest")
        manifest = _compute_manifest(variants, namespace)

        force = bool(args.get("force", False))
        if (
            not force
            and output_path.exists()
            and manifest_path.exists()
            and manifest_path.read_text(encoding="utf-8") == manifest
        ):
            logger.info(f"Skipping up-to-date: {output_path}")
            return

        header = _render_header(namespace, variants)
        output_path.write_text(header, encoding="utf-8")
        manifest_path.write_text(manifest, encoding="utf-8")
        logger.info(
            f"shader_variants_codegen wrote {len(variants)} variant(s) to {output_path}"
        )
