#pragma once

#ifdef __EMSCRIPTEN__
#include <webgpu/webgpu.h>

// Emscripten WebGPU compatibility: provide Dawn-style _INIT macros
// Dawn uses these macros to initialize structs; Emscripten doesn't have them
#ifndef WGPU_INSTANCE_DESCRIPTOR_INIT
#define WGPU_INSTANCE_DESCRIPTOR_INIT {}
#endif
#ifndef WGPU_REQUEST_ADAPTER_CALLBACK_INFO_INIT
#define WGPU_REQUEST_ADAPTER_CALLBACK_INFO_INIT {}
#endif
#ifndef WGPU_DEVICE_DESCRIPTOR_INIT
#define WGPU_DEVICE_DESCRIPTOR_INIT {}
#endif
#ifndef WGPU_DEVICE_LOST_CALLBACK_INFO_INIT
#define WGPU_DEVICE_LOST_CALLBACK_INFO_INIT {}
#endif
#ifndef WGPU_UNCAPTURED_ERROR_CALLBACK_INFO_INIT
#define WGPU_UNCAPTURED_ERROR_CALLBACK_INFO_INIT {}
#endif
#ifndef WGPU_REQUEST_DEVICE_CALLBACK_INFO_INIT
#define WGPU_REQUEST_DEVICE_CALLBACK_INFO_INIT {}
#endif
#ifndef WGPU_SURFACE_DESCRIPTOR_INIT
#define WGPU_SURFACE_DESCRIPTOR_INIT {}
#endif
#ifndef WGPU_SURFACE_SOURCE_WINDOWS_HWND_INIT
#define WGPU_SURFACE_SOURCE_WINDOWS_HWND_INIT {}
#endif
#ifndef WGPU_SURFACE_SOURCE_XLIB_WINDOW_INIT
#define WGPU_SURFACE_SOURCE_XLIB_WINDOW_INIT {}
#endif
#ifndef WGPU_EMSCRIPTEN_SURFACE_SOURCE_CANVAS_HTML_SELECTOR_INIT
#define WGPU_EMSCRIPTEN_SURFACE_SOURCE_CANVAS_HTML_SELECTOR_INIT {}
#endif
#ifndef WGPU_SURFACE_CAPABILITIES_INIT
#define WGPU_SURFACE_CAPABILITIES_INIT {}
#endif
#ifndef WGPU_SURFACE_TEXTURE_INIT
#define WGPU_SURFACE_TEXTURE_INIT {}
#endif
#ifndef WGPU_SURFACE_CONFIGURATION_INIT
#define WGPU_SURFACE_CONFIGURATION_INIT {}
#endif
#ifndef WGPU_COMMAND_ENCODER_DESCRIPTOR_INIT
#define WGPU_COMMAND_ENCODER_DESCRIPTOR_INIT {}
#endif
#ifndef WGPU_RENDER_PASS_COLOR_ATTACHMENT_INIT
#define WGPU_RENDER_PASS_COLOR_ATTACHMENT_INIT {}
#endif
#ifndef WGPU_RENDER_PASS_DESCRIPTOR_INIT
#define WGPU_RENDER_PASS_DESCRIPTOR_INIT {}
#endif
#ifndef WGPU_COMMAND_BUFFER_DESCRIPTOR_INIT
#define WGPU_COMMAND_BUFFER_DESCRIPTOR_INIT {}
#endif
#ifndef WGPU_SHADER_SOURCE_WGSL_INIT
#define WGPU_SHADER_SOURCE_WGSL_INIT {}
#endif

#else
#include <dawn/webgpu.h>
#endif
